name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - run: npm install
      - run: npm run build

      - name: Deploy Storybook to GitHub Pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "GH Actions Bot"
          git config user.email "actions@github.com"
          git remote set-url origin https://${GH_PAT}@github.com/Talisson-b99/design-system-ignite.git
          npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
